# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(547, 300)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 70, 541, 221))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.user_name_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.user_name_input.setObjectName("user_name_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.user_name_input)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.user_pass_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.user_pass_input.setObjectName("user_pass_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.user_pass_input)
        self.btn_submit = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_submit.setObjectName("btn_submit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_submit)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(130, 20, 171, 28))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "User Name"))
        self.label_3.setText(_translate("Form", "Password"))
        self.btn_submit.setText(_translate("Form", "Submit"))
        self.label.setText(_translate("Form", "Login Form"))
